### ISSUE TITLE
[darwin] Elasticsearch 5.4 Missing dependency

### ISSUE THREAD

**Issue by nicemaker** [TritonDataCenter/pkgsrc-legacy#512] opened 2017-06-07 17:11 UTC
Hi,
I've tried:
installing elasticsearch-5.4.0...
pkg_install warnings: 0, errors: 2

Got this:
---Jun 07 20:07:36: installing elasticsearch-5.4.0...
pkg_add: no pkg found for 'oracle-jre8-[0-9]*', sorry.
pkg_add: Can't install dependency oracle-jre8-[0-9]*
pkg_add: 1 package addition failed

**Comment by mamash** [comment] 2017-06-07 17:15
How... how did you end up with this? What platform?

**Comment by mamash** [comment] 2017-06-07 17:16
My guess is that you're building yourself and using the Oracle JRE package instead of OpenJDK, however, I'm pretty sure that the Oracle one is not redistributable, so can't be made available in a repository and installed via pkgin.

**Comment by nicemaker** [comment] 2017-06-07 17:20
Hmm, did nothing special, I use Mac OSX 10.12 and did this

```
sudo pkgin update
sudo pkgin install elasticsearch
```

**Comment by nicemaker** [comment] 2017-06-07 17:21
do you mean whatever Oracle JRE I have installed conflicts and i might resolve it by removing it and using OopenJDK?

**Comment by mamash** [comment] 2017-06-07 17:21
No. I'm looking into this.

**Comment by mamash** [comment] 2017-06-07 17:36
The oracle JRE/JDK package should never be used to build out binary packages, because they cannot be redistributed in a binary form due to licensing restrictions. For some reason, the current osx/trunk packages that we build are, so that needs to be fixed.

**Comment by nicemaker** [comment] 2017-06-07 17:37
thanks mamash for responding so quickly

**Comment by mamash** [comment] 2017-06-13 12:47
Just a quick update: this is confirmed as a known bug in *all* packages depending on Java on the Darwin (OS X) platform. The build cluster used to build out the binary packages is not configured in order to provide a proper native Java implementation that pkgsrc would recognize and use.

As an interrim workaround, it is suggested that you install pkgsrc to your system and build elasticsearch (or any other Java package) yourself locally.

**Comment by jperkin** [comment] 2017-06-20 16:22
I've committed https://github.com/NetBSD/pkgsrc/commit/7cf77acd857d84809382295a91e0c486935742a6 and installed the latest Oracle JRE/JDK on the build host.  The next build run will use the native Java rather than one from pkgsrc so these dependency issues will disappear, however manually installing native Java will be required on any target host for the packages to actually work.

**Comment by mamash** [comment] 2017-10-30 13:17
This should be fixed by now. I just fixed an unrelated build issue that will make the package resurface shortly.

**Closed as completed by mamash** 2017-10-30 13:17 UTC
