### ISSUE TITLE
bind - incorrect file dependency path

### ISSUE THREAD

**Issue by tgerczei** [TritonDataCenter/pkgsrc-legacy#465] opened 2017-02-12 09:09 UTC
In '16.4.1' the package 'bind-9.10.4pl5' has an incorrect file path in its SMF service manifest as follows:

&lt;dependency name='config-files' grouping='require_any' restart_on='refresh' type='path'&gt;
      &lt;service_fmri value='file://localhost/etc/named.conf'/&gt;
&lt;/dependency&gt;

This needs the standard prefix '/opt/local' prepended.

**Comment by mamash** [comment] 2017-02-13 12:18
Yes, it's a mismatch between upstream pkgsrc that has /etc hardcoded for bind specifically, and  our local patch that re-introduces /opt/local support for this package. I'll reconcile.

**Comment by jcea** [comment] 2017-02-20 14:12
Hitting this issue myself today.

@mamash , what path will be used in the next revision? "/etc" or "/opt/local/etc"?. I need that info for my ansible scripts.

Thanks!.

**Comment by mamash** [comment] 2017-02-20 14:13
The latter.

**Comment by jcea** [comment] 2017-02-20 14:15
@mamash Please, let me know when you update the package. I think that this SHOULD be backported to 16.4.1 zones.

**Comment by mamash** [comment] 2017-02-21 16:35
This is now fixed in 2016Q4 (and in trunk), the bind packages are set to use a standard $PKG_SYSCONFDIR as expected in pkgsrc.

This was all caused by a legacy decision made by a maintainer back in 2000, which escaped our local patching recently when a update was made to a package in trunk. No more patches are needed now.

**Closed as completed by mamash** 2017-02-21 16:35 UTC

**Comment by tgerczei** [comment] 2017-02-21 18:49
Thanks @mamash !

**Comment by jcea** [comment] 2017-02-22 16:22
Verified. Thanks, @mamash
