### ISSUE TITLE
sun-jre7/syujdk7CHECK_SHLIBS_SUPPORTED=

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc-legacy#39] opened 2013-03-08 14:38 UTC
```
diff --git a/lang/sun-jdk7/Makefile b/lang/sun-jdk7/Makefile
index 6c70633..021dd1d 100644
--- a/lang/sun-jdk7/Makefile
+++ b/lang/sun-jdk7/Makefile
@@ -29,7 +29,7 @@ CHECK_SHLIBS_SUPPORTED=       no
 # XXX: The download page says .tar.gz but sends the file as .gz
 .if ${OPSYS} == "SunOS"
 EXTRACT_OPTS=  -f tar
-EXTRACT_SUFX=  .gz
+EXTRACT_SUFX=  .tar.gz
 .endif

 # The 64-bit Solaris downloads for some inexplicable reason only contain
diff --git a/lang/sun-jdk7/distinfo b/lang/sun-jdk7/distinfo
index d909026..7cd5f22 100644
--- a/lang/sun-jdk7/distinfo
+++ b/lang/sun-jdk7/distinfo
@@ -1,14 +1,8 @@
 $NetBSD: distinfo,v 1.6 2013/03/06 16:58:57 jperkin Exp $

-SHA1 (jdk-7u15-linux-i586.tar.gz) = bf42fd0fd45d6bc3b644f2035410df0eaee32900
-RMD160 (jdk-7u15-linux-i586.tar.gz) = 94342179c7cc88e264743a803399da166637ebd9
-Size (jdk-7u15-linux-i586.tar.gz) = 97486991 bytes
-SHA1 (jdk-7u15-linux-x64.tar.gz) = 1dfa71bc04d3c1ef02aba4a21d6d3031d39c8346
-RMD160 (jdk-7u15-linux-x64.tar.gz) = 5c7532c6b3423f0659fcaae619b47cee9e20ae43
-Size (jdk-7u15-linux-x64.tar.gz) = 96131837 bytes
-SHA1 (jdk-7u15-solaris-i586.gz) = 11788476781accd918c9343344de12e774517bfe
-RMD160 (jdk-7u15-solaris-i586.gz) = 326e56f7067a451c0260f57619e8fdfd9a133c34
-Size (jdk-7u15-solaris-i586.gz) = 96403012 bytes
-SHA1 (jdk-7u15-solaris-x64.gz) = ba2b71f00ab4021213b171994f19f71f92eee7a9
-RMD160 (jdk-7u15-solaris-x64.gz) = a3db29cdd486d3add24f5eff9b1c53ce66a5dec3
-Size (jdk-7u15-solaris-x64.gz) = 15688278 bytes
+SHA1 (jdk-7u15-solaris-i586.tar.gz) = 11788476781accd918c9343344de12e774517bfe
+RMD160 (jdk-7u15-solaris-i586.tar.gz) = 326e56f7067a451c0260f57619e8fdfd9a133c3
+Size (jdk-7u15-solaris-i586.tar.gz) = 96403012 bytes
+SHA1 (jdk-7u15-solaris-x64.tar.gz) = ba2b71f00ab4021213b171994f19f71f92eee7a9
+RMD160 (jdk-7u15-solaris-x64.tar.gz) = a3db29cdd486d3add24f5eff9b1c53ce66a5dec3
+Size (jdk-7u15-solaris-x64.tar.gz) = 15688278 bytes
diff --git a/lang/sun-jre7/Makefile b/lang/sun-jre7/Makefile
index 6e377a2..9b6f4ee 100644
--- a/lang/sun-jre7/Makefile
+++ b/lang/sun-jre7/Makefile
@@ -8,7 +8,7 @@
 DISTNAME=      jre-7u15-${DIST_OS}-${DIST_ARCH}
 PKGNAME=       sun-jre7-7.0.15
 EXTRACT_OPTS=-f tar
-EXTRACT_SUFX=.gz
+EXTRACT_SUFX=.tar.gz
 MASTER_SITES=  # empty

 LICENSE=       oracle-binary-code-license
diff --git a/lang/sun-jre7/distinfo b/lang/sun-jre7/distinfo
index 17d3701..a4975e9 100644
--- a/lang/sun-jre7/distinfo
+++ b/lang/sun-jre7/distinfo
@@ -1,17 +1,8 @@
 $NetBSD: distinfo,v 1.8 2013/03/06 16:21:13 jperkin Exp $

-SHA1 (UnlimitedJCEPolicyJDK7.zip) = 7d3c9ee89536b82cd21c680088b1bced16017253
-RMD160 (UnlimitedJCEPolicyJDK7.zip) = a4a6a284579f43d2df3532d279e143d2f03c2c3f
-Size (UnlimitedJCEPolicyJDK7.zip) = 7426 bytes
-SHA1 (jre-7u15-linux-i586.tar.gz) = 9d2680eb7cb07524f1ac43d517d221caa5aa08da
-RMD160 (jre-7u15-linux-i586.tar.gz) = 0f588dc329d70bb1e5b9c95e208df8d85bf01569
-Size (jre-7u15-linux-i586.tar.gz) = 48129053 bytes
-SHA1 (jre-7u15-linux-x64.tar.gz) = cfd274e6a18c135f3f16955388127fb48ebecb37
-RMD160 (jre-7u15-linux-x64.tar.gz) = b453d346173c7583d948856e54c61a02fa6893fe
-Size (jre-7u15-linux-x64.tar.gz) = 46794487 bytes
-SHA1 (jre-7u15-solaris-i586.gz) = a99e1cd8c704961447aa99ef5f35323437aa1363
-RMD160 (jre-7u15-solaris-i586.gz) = b65b2e2898dd27707496ac4ad71c9efd6abd6909
-Size (jre-7u15-solaris-i586.gz) = 47614844 bytes
-SHA1 (jre-7u15-solaris-x64.gz) = c364fdfa72ad6433db9b551c54c1914afb47545d
-RMD160 (jre-7u15-solaris-x64.gz) = 83218ba2f4494e1b2522dccb9459833e62aa7e5b
```

**Comment by jperkin** [comment] 2013-03-08 15:10
Duplicate of #40.

**Closed as completed by jperkin** 2013-03-08 15:10 UTC
