### ISSUE TITLE
2013Q2: apache-tomcat-6 install exits with code 1 even though it installs

### ISSUE THREAD

**Issue by AlainODea** [TritonDataCenter/pkgsrc-legacy#72] opened 2013-09-06 03:16 UTC
Here is a transcript of a session where I reproduce this.

```
[root@50695c08-b34a-4a20-94b1-0d0d1894c233 ~]# /opt/local/bin/pkgin -y install apache-tomcat-6
calculating dependencies... done.

nothing to upgrade.
13 packages to be installed: libfontenc-1.1.2 mkfontscale-1.1.0nb2 mkfontdir-1.0.7 encodings-1.0.4nb1 libXfixes-5.0.1 zip-3.0nb2 unzip-6.0nb1 libXtst-1.2.2 libXrender-0.9.8 libXi-1.7.2 dejavu-ttf-2.33 openjdk7-1.7.21nb3 apache-tomcat-6.0.37 (80M to download, 176M to install)

downloading packages...
libfontenc-1.1.2.tgz                                     100%   31KB  30.8KB/s  30.8KB/s   00:00    
mkfontscale-1.1.0nb2.tgz                                 100%   21KB  20.8KB/s  20.8KB/s   00:00    
mkfontdir-1.0.7.tgz                                      100% 4878     4.8KB/s   4.8KB/s   00:00    
encodings-1.0.4nb1.tgz                                   100%  568KB 568.3KB/s 568.3KB/s   00:00    
libXfixes-5.0.1.tgz                                      100%   21KB  21.1KB/s  21.1KB/s   00:00    
zip-3.0nb2.tgz                                           100%  259KB 259.4KB/s 259.4KB/s   00:00    
unzip-6.0nb1.tgz                                         100%  162KB 161.9KB/s 161.9KB/s   00:00    
libXtst-1.2.2.tgz                                        100%   41KB  40.5KB/s  40.5KB/s   00:00    
libXrender-0.9.8.tgz                                     100%   47KB  47.5KB/s  47.5KB/s   00:00    
libXi-1.7.2.tgz                                          100%  159KB 158.6KB/s 158.6KB/s   00:00    
dejavu-ttf-2.33.tgz                                      100% 4813KB   4.7MB/s   4.7MB/s   00:00    
openjdk7-1.7.21nb3.tgz                                   100%   68MB  67.5MB/s  67.5MB/s   00:00    
apache-tomcat-6.0.37.tgz                                 100% 6745KB   6.6MB/s   6.6MB/s   00:01    
installing packages...
installing libfontenc-1.1.2...
installing mkfontscale-1.1.0nb2...
installing mkfontdir-1.0.7...
installing encodings-1.0.4nb1...
installing libXfixes-5.0.1...
installing zip-3.0nb2...
installing unzip-6.0nb1...
installing libXtst-1.2.2...
installing libXrender-0.9.8...
installing libXi-1.7.2...
installing dejavu-ttf-2.33...
dejavu-ttf-2.33: copying /opt/local/share/examples/dejavu-ttf/fontconfig-conf.d/20-unhint-small-dejavu-sans-mono.conf to /opt/local/etc/fontconfig/conf.d/20-unhint-small-dejavu-sans-mono.conf
dejavu-ttf-2.33: copying /opt/local/share/examples/dejavu-ttf/fontconfig-conf.d/20-unhint-small-dejavu-sans.conf to /opt/local/etc/fontconfig/conf.d/20-unhint-small-dejavu-sans.conf
dejavu-ttf-2.33: copying /opt/local/share/examples/dejavu-ttf/fontconfig-conf.d/20-unhint-small-dejavu-serif.conf to /opt/local/etc/fontconfig/conf.d/20-unhint-small-dejavu-serif.conf
dejavu-ttf-2.33: copying /opt/local/share/examples/dejavu-ttf/fontconfig-conf.d/57-dejavu-sans-mono.conf to /opt/local/etc/fontconfig/conf.d/57-dejavu-sans-mono.conf
dejavu-ttf-2.33: copying /opt/local/share/examples/dejavu-ttf/fontconfig-conf.d/57-dejavu-sans.conf to /opt/local/etc/fontconfig/conf.d/57-dejavu-sans.conf
dejavu-ttf-2.33: copying /opt/local/share/examples/dejavu-ttf/fontconfig-conf.d/57-dejavu-serif.conf to /opt/local/etc/fontconfig/conf.d/57-dejavu-serif.conf
dejavu-ttf-2.33: updating font database in /opt/local/lib/X11/fonts/TTF (ttf)
dejavu-ttf-2.33: updating font database in /opt/local/lib/X11/fonts/TTF (x11)
installing openjdk7-1.7.21nb3...
installing apache-tomcat-6.0.37...
apache-tomcat-6.0.37: Creating group ``tomcat''
apache-tomcat-6.0.37: Creating user ``tomcat''
passwd: password information changed for tomcat
apache-tomcat-6.0.37: copying /opt/local/share/examples/tomcat/catalina.policy to /opt/local/share/tomcat/conf/catalina.policy
apache-tomcat-6.0.37: copying /opt/local/share/examples/tomcat/catalina.properties to /opt/local/share/tomcat/conf/catalina.properties
apache-tomcat-6.0.37: copying /opt/local/share/examples/tomcat/context.xml to /opt/local/share/tomcat/conf/context.xml
apache-tomcat-6.0.37: copying /opt/local/share/examples/tomcat/logging.properties to /opt/local/share/tomcat/conf/logging.properties
apache-tomcat-6.0.37: copying /opt/local/share/examples/tomcat/server.xml to /opt/local/share/tomcat/conf/server.xml
apache-tomcat-6.0.37: copying /opt/local/share/examples/tomcat/tomcat-users.xml to /opt/local/share/tomcat/conf/tomcat-users.xml
apache-tomcat-6.0.37: copying /opt/local/share/examples/tomcat/web.xml to /opt/local/share/tomcat/conf/web.xml
===========================================================================
The following files should be created for apache-tomcat-6.0.37:

        /etc/rc.d/tomcat (m=0755)
            [/opt/local/share/examples/rc.d/tomcat]

===========================================================================
//////////////////////////////////////////////////////////////////////////////

This package is SMF enabled, which means you can use SMF to 'enable',
'disable' or 'restart' the persistent daemon process, e.g.:

  svcadm enable tomcat:default

The SMF manifest was automatically imported now.

See our wiki on what's SMF and how to use it to your advantage:

  http://wiki.joyent.com/display/smart/About+the+Service+Management+Facility

//////////////////////////////////////////////////////////////////////////////
===========================================================================
$NetBSD: MESSAGE,v 1.1 2010/01/28 12:16:45 spz Exp $

The /opt/local/share/tomcat/webapps directory will be mercilessly mangled
in updates, so pick a different directory for your own local appBase
(in /opt/local/share/tomcat/conf/server.xml). You have been warned. :)

===========================================================================
pkg_install warnings: 0, errors: 0
reading local summary...
processing local summary...
updating database: 100%
marking apache-tomcat-6.0.37 as non auto-removable
[root@50695c08-b34a-4a20-94b1-0d0d1894c233 ~]# echo $?
1
```

**Comment by jperkin** [comment] 2013-09-06 07:30
This is a duplicate of joyent/pkgsrc-joyent#7 and is fixed in newer versions of `pkg_add`.

**Closed as completed by jperkin** 2013-09-06 07:30 UTC

**Comment by AlainODea** [comment] 2013-09-06 10:40
Thank you @jperkin :)
