### ISSUE TITLE
Issues handling exceptions with GCC libraries built against SDC 6.5

### ISSUE THREAD

**Issue by jjlawren** [TritonDataCenter/pkgsrc-legacy#74] opened 2013-09-09 01:22 UTC
I've had issues with g++ compiled binaries coring when any exception is thrown. Overriding the libraries provided with the _gcc47/gcc47-libs_ packages with 'LD_PRELOAD=/usr/sfw/lib/amd64/libgcc_s.so.1' seems to be a workaround and solves the coring issues, but it's not an ideal fix.

A little more background from someone that obviously knows quite a bit more than I:

_Keith Wesolowski said:_
"This is very likely a problem with the pkgsrc gcc libraries. It's not a
platform bug. We believe that the problem is caused by using exceptions
with a gcc library built against an SDC 6.5 platform. In order to solve
this, we'll need to start building pkgsrc packages against SDC 7."

**Comment by jperkin** [comment] 2013-09-09 09:02
It's not clear to me what the root of the problem is here, but @rmustacc has previously indicated that we cannot do builds on SDC7 yet as there are backwards-incompatible changes which would mean our packages would no longer work on SDC6.5.

/cc @wesolows

**Comment by jjlawren** [comment] 2013-09-12 14:50
I'm not sure I understand the problem, either. The LD_PRELOAD override allows the binary to run, but some functionality does fail, such as when it tries to call an external command (bash script in this case):
ld.so.1: bash: fatal: /usr/sfw/lib/amd64/libgcc_s.so.1: wrong ELF class: ELFCLASS64

However, trying to load the original binary with the 32 bit version fails immediately:
ld.so.1: aria2c: fatal: /usr/sfw/lib/libgcc_s.so.1: wrong ELF class: ELFCLASS32

It sounds like the suggestion from @wesolows is more of a long-term fix. Can anyone suggest a workaround for now?

**Comment by rmustacc** [comment] 2013-09-12 16:05
@jjlawren You'll want so specify `LD_PRELOAD_32` and `LD_PRELOAD_64` to cover both sets of elf types. Otherwise `LD_PRELOAD` applies to both 32-bit and 64-bit binaries so specifying a full path there will end in pain.

**Comment by jjlawren** [comment] 2013-09-12 18:54
This worked as a workaround. Thanks for the tip.

**Comment by mamash** [comment] 2014-03-15 10:51
Erroneously closed by Github.

**Comment by jperkin** [comment] 2016-06-02 13:26
Sorry it's taken so long to get around to looking at this issue.  I've tried to reproduce this with the latest pkgsrc release and cannot, so something along the way has made this disappear, possibly since we started building on a newer SmartOS release and fixed various issues with our compiler (as well as upgrading to GCC 4.9).

I'm going to close this for now, but if any other issues come up with aria2 please let us know, thanks.

**Closed as completed by jperkin** 2016-06-02 13:26 UTC

**Comment by jjlawren** [comment] 2016-06-02 14:02
Since I opened the case, aria2 has made it into pkgsrc and has been working without workarounds. Thanks for looking into this either way.
