### ISSUE TITLE
GNU coreutils link (?) bug in stdbuf

### ISSUE THREAD

**Issue by RantyDave** [TritonDataCenter/pkgsrc-legacy#443] opened 2016-12-20 07:18 UTC
Following 'pkgin in coreutils'

```
[root@t1700 ~]# stdbuf -o 0 true
ld.so.1: true: fatal: /opt/local/libexec/coreutils/libstdbuf.so: wrong ELF class: ELFCLASS64
Killed
```

**Comment by mamash** [comment] 2017-01-05 12:12
Which platform and/or package set is this happening on? I can't seem to reproduce.

**Comment by jperkin** [comment] 2017-05-25 14:52
I've tried to reproduce this on all of the i386, x86_64 and multiarch sets for both 2016Q3 and 2015Q4 which are the two most likely repositories based on when this ticket was created, and can't reproduce, so I'm going to close this in lieu of more specific information on how to reproduce it.

**Closed as completed by jperkin** 2017-05-25 14:52 UTC
